"""empty message

Revision ID: 7fb295d2a7c3
Revises: 
Create Date: 2023-02-24 15:08:02.004538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb295d2a7c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('booking_no',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('otp',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('ticket_type',
               existing_type=mysql.VARCHAR(length=90),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('total_seats',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('theater', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('phone_no',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('phone_no',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('theater', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.alter_column('total_seats',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('ticket_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=90),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('otp',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('booking_no',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
